; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_flags = 
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
	-D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
	-D CONFIG_ASYNC_TCP_PRIORITY=1
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=1024
	-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
	-D WS_MAX_QUEUED_MESSAGES=1024
lib_deps = 
	bblanchon/ArduinoJson @ ^7.0.4
	ayushsharma82/ElegantOTA @ ^3.1.0
	links2004/WebSockets @ ^2.4.1
	plerup/EspSoftwareSerial @ ^8.2.0
	ldab/esp32_ftpclient @ ^0.1.4
